import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'OUTOFREACH3D™ – Create, Customize, and Sell products on IMVU, Second Life, Sims 4, Roblox, Inzoi, GTA 6 and more',
  description: 'Create 3D items for IMVU, Second Life, Sims 4, Roblox, Inzoi, GTA 6 and more. Create once, wear & sell everywhere.',
  keywords: [
    'virtual product creation',
    '3D design for games',
    'IMVU creator tools',
    'Second Life fashion',
    'Sims 4 mesh editor',
    'Roblox UGC',
    'GTA 6 avatar assets',
    'Inzoi customization',
    'AI for 3D modeling',
    'easy 3D clothing tools',
    'create digital fashion',
    'game modding tools',
    '3D creating',
    'Create for IMVU',
    'Create for Second Life',
    'Create for Sims 4',
    'Create for Roblox',
    'Create for Inzoi',
    'Create for GTA 6',
    '3D modeling',
    'AI for IMVU',
    'AI for Second Life',
    'AI for Sims 4',
    'AI for Roblox',
    'AI for Inzoi',
    'AI for GTA 6',
    'Create clothes for IMVU',
    'Create clothes for Second Life',
    'Create clothes for Sims 4',
    'Create clothes for Roblox',
    'Create clothes for Inzoi',
    'Create clothes for GTA 6',
    'IMVU',
    'Second Life',
    'Sims 4',
    'Roblox',
    'GTA 6',
    '3D design',
    'digital assets'
  ],
  openGraph: {
    title: 'OUTOFREACH3D™ - Create Products for the Virtual World',
    description: 'OOR3D™ gives creators the power to design, customize and sell digital wearables for IMVU, Second Life, Sims 4, and more — without complicated 3D software.',
    url: 'https://outofreach3d.com',
    siteName: 'OUTOFREACH3D',
    images: [
      {
        url: 'https://outofreach3d.com/preview-image.jpg',
        width: 1200,
        height: 630,
        alt: 'OUTOFREACH3D™ - Create 3D Products for the virtual world'
      }
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'OUTOFREACH3D™ - Create Products for the Virtual World',
    description: 'Create virtual products for IMVU, Second Life, Sims 4, Roblox, Inzoi, GTA 6 and more. Design once, sell everywhere.',
    images: ['https://outofreach3d.com/preview-image.jpg'],
  },
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  manifest: '/site.webmanifest',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  other: {
    'theme-color': '#000000',
  },
}
