import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Clothes & Products for IMVU, Sims 4 & More - OUTOFREACH3D™',
  description: 'The all-in-one workspace to create, customize, and sell 3D products for IMVU, Second Life, Sims 4, Roblox, Inzoi, GTA 6, and more.',
  keywords: [
    'virtual product creation',
    '3D design for games',
    'IMVU creator tools',
    'Second Life fashion',
    'Sims 4 mesh editor',
    'Roblox UGC',
    'GTA 6 avatar assets',
    'Inzoi customization',
    'AI for 3D modeling',
    'easy 3D clothing tools',
    'create digital fashion',
    'game modding tools',
    '3D creating',
    'Create for IMVU',
    'Create for Second Life',
    'Create for Sims 4',
    'Create for Roblox',
    'Create for Inzoi',
    'Create for GTA 6',
    '3D modeling',
    'AI for IMVU',
    'AI for Second Life',
    'AI for Sims 4',
    'AI for Roblox',
    'AI for Inzoi',
    'AI for GTA 6',
    'Create clothes for IMVU',
    'Create clothes for Second Life',
    'Create clothes for Sims 4',
    'Create clothes for Roblox',
    'Create clothes for Inzoi',
    'Create clothes for GTA 6',
    'IMVU',
    'Second Life',
    'Sims 4',
    'Roblox',
    'GTA 6',
    '3D design',
    'digital assets'
  ],
  openGraph: {
    title: 'Create Products for your Avatar - IMVU, Second Life & Sims 4',
    description: 'OOR3D is your complete workspace for creating products for your characters in video games. Everything you need to design, customize, and export avatar products for IMVU, Second Life, Sims 4, and every virtual platform. Remix existing products or create your own from scratch.',
    url: 'https://outofreach3d.com',
    siteName: 'OUTOFREACH3D™',
    images: [
      {
        url: 'https://assets.oor3d.com/img/card-actions/The%20universal%20virtual%20world%20creator%20workspace.png',
        width: 1200,
        height: 630,
        alt: 'OOR3D - Create Products for Your Avatar'
      }
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Create Products for your Avatar - IMVU, Second Life & Sims 4',
    description: 'OOR3D is your complete workspace for creating products for your characters in video games. Everything you need to design, customize, and export avatar products for IMVU, Second Life, Sims 4, and every virtual platform. Remix existing products or create your own from scratch.',
    images: ['https://assets.oor3d.com/img/card-actions/The%20universal%20virtual%20world%20creator%20workspace.png'],
  },
  icons: {
    icon: [
      { url: '/icons/favicon.svg', type: 'image/svg+xml' },
      { url: '/icons/favicon.ico', sizes: 'any' },
    ],
    shortcut: '/icons/favicon.ico',
    apple: 'https://assets.oor3d.com/logo/OOR-discord.png',
  },
  manifest: '/icons/site.webmanifest',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  other: {
    'theme-color': '#000000',
  },
}
